### ISSUE TITLE
Synchronize PSR12 configuration with symplify/easy-coding-standard

### ISSUE THREAD

**Issue by drupol** [drupol/phpcsfixer-configs-php#1]
While checking out ECS from @TomasVotruba, I noticed some differences in the PSR12 configuration ruleset.

This issue is created to fix the discrepancy between drupol/phpcsfixer-configs-php and ECS.

**Comment by TomasVotruba** [comment]
I see you're tryting to make similar sets as ECS has.

What do you think about switch to ECS completely and improve sets or even add sets there?

It's been used by huge community of programmers and your contribution would help big group of PHP devs.

**Comment by drupol** [comment]
Hi Tomas,

I will investigate more and see how I could integrate ECS instead.

Thanks for your reactivity, it's always a pleasure :)

**Comment by drupol** [comment]
Opening that issue https://github.com/symplify/symplify/pull/1927 as a follow-up and revert the following one.

**Comment by TomasVotruba** [comment]
Hey! You were lucky I was just online GitHubbing :D

This might help you to get in quickly [How to Migrate From PHP CS Fixer to EasyCodingStandard in 6 Steps](https://www.tomasvotruba.com/blog/2018/06/07/how-to-migrate-from-php-cs-fixer-to-easy-coding-standard/)

Thanks for PR, I'll check it!
