### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupol/phpcsfixer-configs-php#54]
Hi @drupol,

Could you please make a new release for `phpcsfixer-configs-php` please?

When using `phpcsfixer-configs-drupal`, it is not possible to use the dev version of `phpcsfixer-configs-php` with Composer.

Thanks :)

**Comment by drupol** [comment]
Job done !

**Comment by FlorentTorregrosa** [comment]
Thanks :)
