### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupol/phpcsfixer-configs-php#73]
Hi,

Would it be possible to tag new releases for this repository and for https://github.com/drupol/phpcsfixer-configs-drupal please?

**Comment by FlorentTorregrosa** [comment]
No, please bot, keep it opened.

**Comment by FlorentTorregrosa** [comment]
@drupol , Hi,

I would like to open a discussion. Maybe also with @WengerK?

You are very reactive on PR, thank you :pray:.

But from what I remember, you told me that you are no more using https://github.com/drupol/phpcsfixer-configs-drupal and https://github.com/drupol/phpcsfixer-configs-php, and I don't want to bother you making new releases or other maintenance stuff if you are not using it anymore.

So I would like to ask you if you would be ok if I open a repository on Drupal.org that would become the official phpcsfixer configuration for Drupal, or maybe it could be integrated in Coder?

If you are ok with this proposal, I will then need to discuss with Coder maintainers and or Gitlab CI on drupal.org team to know if it would interest them. But I wanted to ask you first of course.

Thanks for any reply :)

**Comment by drupol** [comment]
Hello Florent,

As this project is open-source, I have no objections to it being forked or further improved. Feel free to proceed if you believe that’s the best approach. Although I no longer use Drupal, moving the project to a more appropriate environment might be a good idea.

I do have only 2 requests:
- Please ensure that the Git history remains intact, so we can properly trace the project's origins and authorship.
- Once the transition is complete, I would like to archive this repository to avoid any duplication and ensure clarity.

**Comment by WengerK** [comment]
For my point of view, I'm not sure if a none-module should be on drupal.org. What is the recommendation from Drupal.org team ?

See drush being on GitHub Nop ?

**Comment by FlorentTorregrosa** [comment]
Hi,

Thanks both of you for your feedbacks.

On https://www.drupal.org/node/add there is the "General project", which results in a package automatically published on packagist.

Drush is on Github, there is also Coder. So it is not mandatory.

My main point is to not have @drupol bothered if he does not have the time.

And second point, discuss with Coder and/or drupal.org team what is the best to promote the work done here to become something official if possible and avoid potential duplicated work.

I will reached them so we can continue the discussion.

And without hurry :)

**Comment by WengerK** [comment]
Thanks for your answer, also in order to have a better reactivity, we could discuss to pass you as maintainer (alongside with me) for this project and also create a _Channel on the Drupal Slack_ (to ease our collaboration but also to be transparent with the Drupal community and how to reach us.

For my point of view, many project outside of modules are on Github and I would prefer keeping this repo on Github:
- Coder: https://github.com/pfrenssen/coder
- Drush: https://github.com/drush-ops/drush
- Drupal Rector: https://github.com/palantirnet/drupal-rector

Waiting on your answers from the Drupal Association Team

**Comment by FlorentTorregrosa** [comment]
For [drupol/phpcsfixer-configs-drupal](https://github.com/drupol/phpcsfixer-configs-drupal), because the 2 last commits did not update CHANGELOG.md: https://github.com/drupol/phpcsfixer-configs-drupal/commits/master/

Hum, I don't remember having problem with the requirements on the drupal config repository.

**Comment by FlorentTorregrosa** [comment]
So, I asked one of the Coder maintainer (I forgot to ask permission to mention him).

As in Coder, there is the tool to also fix the CS (since 4/5 years), there is no need to have a second tool to handle CS alongside Coder.

So I guess, we can keep the two repositories like they are right now. Just keeping it alive and maintained.

And if you are ok to give me the access so I can make merge and releases, I would be able to do it myself.

In fact, when it is just configuration adjustments, I am not blocked because I already have my overrides in https://gitlab.com/florenttorregrosa-drupal/docker-drupal-project/-/tree/11.x/scripts/quality/phpcs_fixer?ref_type=heads, it is just that I want my overrides to be only for my personal preferences not official changes :). I am blocked only when new code is needed for new rules, which happens not very often :)

**Comment by drupol** [comment]
I just invited you.

**Comment by FlorentTorregrosa** [comment]
Thanks, invitation accepted.

**Comment by FlorentTorregrosa** [comment]
Currently removing Scrutinizer in https://github.com/drupol/phpcsfixer-configs-php/pull/74 as it is broken and also removed in the drupal repository.

But it seems that a task is still expected and I think I don't have permissions to access CI config for this repository.

**Comment by drupol** [comment]
Can we close this issue now ?

**Comment by FlorentTorregrosa** [comment]
Hi,
I will try to get the time to make a new release soon.
I will close the issue then.

**Comment by FlorentTorregrosa** [comment]
I wanted to do a last doc update before release, but I had to create a PR and not possible to merge it: https://github.com/drupol/phpcsfixer-configs-php/pull/75#issuecomment-2396663207

**Comment by FlorentTorregrosa** [comment]
https://github.com/drupol/phpcsfixer-configs-php/releases/tag/2.0.21

**Comment by FlorentTorregrosa** [comment]
https://github.com/drupol/phpcsfixer-configs-php/actions/runs/11214702023/job/31170323301

Failure because when I created the release, I created the tag with Github UI, not by Git push.

**Comment by FlorentTorregrosa** [comment]
Good now, I have deleted release and tag, and then repushed a tag from CLI.
